name: racformerfix
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - binutils=2.44=h4852527_2
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cccl=12.4.127=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-driver-dev=12.4.127=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.8.0=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=hc01ab50_4
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gcc=11.2.0=h702ea55_10
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.1.2=py38heeb90bb_0
  - graphite2=1.3.14=h295c915_1
  - gxx=11.2.0=h702ea55_10
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=h42c8aad_2
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.1=h13d4d48_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.28=h166bdaf_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.18=hd6dcaed_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py38h5eee18b_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - pytorch=2.0.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - sympy=1.13.3=py38h06a4308_0
  - sysroot_linux-64=2.34=h087de78_2
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchtriton=2.0.0=py38
  - torchvision=0.15.0=py38_cu118
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - asttokens==3.0.0
      - attrs==25.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - black==24.8.0
      - blinker==1.8.2
      - cachetools==5.5.2
      - cffi==1.17.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - descartes==1.1.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - fire==0.7.1
      - flake8==7.1.2
      - flash-attn==2.6.3
      - flask==3.0.3
      - fonttools==4.57.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.36.0
      - lyft-dataset-sdk==0.0.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmcls==0.25.0
      - mmdet==2.28.2
      - mmdet3d==1.0.0rc6
      - mmengine==0.10.7
      - mmsegmentation==0.30.0
      - model-index==0.1.11
      - mypy-extensions==1.1.0
      - narwhals==1.42.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==2.2
      - ninja==1.13.0
      - numba==0.53.0
      - numpy==1.23.5
      - nuscenes-devkit==1.1.11
      - oauthlib==3.3.1
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.5
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pip==25.0.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.3.1
      - pluggy==1.5.0
      - plyfile==1.0.3
      - prettytable==3.11.0
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pyflakes==3.2.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - referencing==0.35.1
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rich==13.4.2
      - rpds-py==0.20.1
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - setuptools==75.3.2
      - shapely==1.8.5.post1
      - six==1.17.0
      - soupsieve==2.7
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tomli==2.3.0
      - tqdm==4.65.2
      - traitlets==5.14.3
      - trimesh==2.35.39
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - werkzeug==3.0.6
      - wheel==0.45.1
      - widgetsnbextension==4.0.14
      - yapf==0.43.0
      - zipp==3.20.2
prefix: /srv/nfs/shared/gnmp/miniconda3/envs/racformerfix
